### ISSUE TITLE
/stats shows median described score as 100%

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#643]
Seems entirely unlikely that the median of all described scores is 100% Would be awesome but worth confirming. This might be a case where median is not actually the greatest if all others under P50 are say 0. In any event, probably worth a quick look to validate that the number is legit

**Comment by geneh** [comment]
Resolved by https://github.com/clearlydefined/service/issues/639

**Comment by geneh** [comment]
The issue is still unresolved and reproducible in dev env.

**Comment by nellshamrell** [comment]
Confirmed this is still an issue by visiting [the stats page](https://clearlydefined.io/stats)
